apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedules-server
spec:
  replicas: 1
  selector:
    matchLabels:
      id: schedules-server
      type: main
  template:
    metadata:
      labels:
        id: schedules-server
        type: main
    spec:
      containers:
        - name: prisma
          image: prismagraphql/prisma:1.34
          imagePullPolicy: Always
          env:
            - name: PRISMA_CONFIG
          value: |
            port: 4466
            databases:
              default:
                connector: mongo
                uri: mongodb://prisma:prisma@mongo
          resources:
            limits:
              cpu: 100m
              memory: 100Mi

        - name: mongo
          image: mongo:3.6
          imagePullPolicy: Always
          environment:
            MONGO_INITDB_ROOT_USERNAME: prisma
            MONGO_INITDB_ROOT_PASSWORD: prisma
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
      # - image: YOUR_LOCAL_DOCKER_REGISTRY:5000/schedules-server
      #   imagePullPolicy: Always
      #   name: schedules-server
      #   resources:
      #     limits:
      #       cpu: 100m
      #       memory: 100Mi
