const typesOfDay = {
    all: 'все',
    BT: 'К',
    S: 'ВУ',
    AS: 'ОУ',
    UR: 'НН',
    A: 'П',
    MA: 'Г',
    SV: 'РП',
    D: 'Б',
    V: 'О',
    CC: 'ОР',
    AV: 'А',
    O: 'С',
    NT: 'Н',
}

//Helper
// 'Business Trip (BT)': 'Служеб. командировки (К)',
// 'Scholastic (S)': 'Выходной по учебе (ВУ)',
// 'Addition Scholastic (AS)': 'Учебный доп. отпуск (ОУ)',
// 'Unknown reason (UR)': 'Невыясненные причины (НН)',
// 'Absenteeism (A)': 'Прогул (П)',
// 'Manager allow (MA)': 'Гос. обязанность (Г)',
// 'Scholastic vacation (SV)': 'Праздн. день (РП)',
// 'Disease (D)': 'Болезнь (Б)',
// 'Vacation (V)': 'Отпуск (О)',
// 'Child care (CC)': 'Уход за ребенком (ОР)',
// 'Administration vacation (AV)': 'Адм. отпуск (А)',
// 'Overtime (O)': 'Сверхур. работы (С)',
// 'Night time (NT)': 'Ночное время (Н)',
// 'Working (W)': 'Фак. отраб.(Ф)',